import { Archetype } from './types';

export const archetypes: Archetype[] = [
  {
    id: 'panic-seller',
    title: 'Panic Seller',
    emoji: '😱',
    tagline: 'First to sell, last to profit.',
    description: 'You have an extraordinary talent for selling at the exact bottom. Your hands are made of wet tissue paper and your portfolio is a monument to impulsive exits. But hey, at least you sleep well at night... right?',
    strengths: ['Quick reflexes', 'Capital preservation instinct', 'Emotional awareness'],
    weaknesses: ['Zero patience', 'FOMO after selling', 'Buys back higher'],
    memeObservation: 'You sold ETH at $80 and bought back at $4,000. Your trading history is a comedy special.',
    emotionalTendency: 'Peaks of euphoria followed by valleys of regret. Your portfolio chart looks like a heartbeat monitor.',
    gradient: 'linear-gradient(135deg, #FB7185 0%, #F43F5E 50%, #E11D48 100%)',
    gradientColors: ['#FB7185', '#E11D48'],
    accentColor: '#FB7185',
    traits: [
      { name: 'Risk Appetite', value: 25, color: '#FB7185' },
      { name: 'Conviction', value: 15, color: '#F43F5E' },
      { name: 'Emotional Stability', value: 10, color: '#E11D48' },
      { name: 'Meme Exposure', value: 60, color: '#FF4FD8' },
      { name: 'Patience', value: 5, color: '#7C5CFF' },
      { name: 'Diversification', value: 70, color: '#00D4FF' },
    ],
    icon: '📉',
    mood: 'anxious',
  },
  {
    id: 'diamond-hands-monk',
    title: 'Diamond Hands Monk',
    emoji: '💎',
    tagline: 'Inner peace through unrealized gains.',
    description: 'You bought in 2021 and haven\'t checked the chart since. Your conviction is unshakeable, your patience is legendary, and your cost basis is a mystery even to you. You\'ve achieved financial zen.',
    strengths: ['Unbreakable conviction', 'Long-term vision', 'Immune to FUD'],
    weaknesses: ['Might be holding a dead coin', 'Forgets wallet passwords', 'Misses exit opportunities'],
    memeObservation: 'You bought dips with confidence and sold pumps with regret. Just kidding—you never sell.',
    emotionalTendency: 'Flat-line calm. Nothing moves you. Not even a 90% drawdown.',
    gradient: 'linear-gradient(135deg, #818CF8 0%, #6366F1 50%, #4F46E5 100%)',
    gradientColors: ['#818CF8', '#4F46E5'],
    accentColor: '#818CF8',
    traits: [
      { name: 'Risk Appetite', value: 65, color: '#818CF8' },
      { name: 'Conviction', value: 98, color: '#6366F1' },
      { name: 'Emotional Stability', value: 95, color: '#4F46E5' },
      { name: 'Meme Exposure', value: 20, color: '#FF4FD8' },
      { name: 'Patience', value: 100, color: '#7C5CFF' },
      { name: 'Diversification', value: 30, color: '#00D4FF' },
    ],
    icon: '🧘',
    mood: 'zen',
  },
  {
    id: 'meme-coin-goblin',
    title: 'Meme Coin Goblin',
    emoji: '👺',
    tagline: 'Degen is not a strategy. It\'s a lifestyle.',
    description: 'Your portfolio reads like a fever dream. You\'ve bought tokens named after dogs, frogs, cats, and at least three types of food. Your Solana wallet is a museum of rugged projects and chaotic gains.',
    strengths: ['Trend detection', 'Community instinct', 'Unlimited optimism'],
    weaknesses: ['Zero due diligence', 'Rug magnet', 'Portfolio is 90% dead tokens'],
    memeObservation: 'Your portfolio has more dead meme coins than a crypto graveyard. You don\'t invest—you collect digital tombstones.',
    emotionalTendency: 'Pure chaotic energy. Every day is either "WE\'RE GOING TO THE MOON" or "WHY DID I BUY THIS."',
    gradient: 'linear-gradient(135deg, #4ADE80 0%, #22C55E 50%, #16A34A 100%)',
    gradientColors: ['#4ADE80', '#16A34A'],
    accentColor: '#4ADE80',
    traits: [
      { name: 'Risk Appetite', value: 95, color: '#4ADE80' },
      { name: 'Conviction', value: 40, color: '#22C55E' },
      { name: 'Emotional Stability', value: 20, color: '#16A34A' },
      { name: 'Meme Exposure', value: 100, color: '#FF4FD8' },
      { name: 'Patience', value: 10, color: '#7C5CFF' },
      { name: 'Diversification', value: 95, color: '#00D4FF' },
    ],
    icon: '🐸',
    mood: 'chaotic',
  },
  {
    id: 'exit-liquidity',
    title: 'Exit Liquidity Provider',
    emoji: '🚪',
    tagline: 'Always buying someone else\'s top.',
    description: 'You have an uncanny ability to buy at the exact top of every pump. Whales thank you for your service. You are the exit liquidity that makes the crypto ecosystem function.',
    strengths: ['Excellent market timing (inverse)', 'Consistent behavior', 'Supporting the ecosystem'],
    weaknesses: ['Buys every top', 'Follows influencer calls', 'Portfolio is underwater'],
    memeObservation: 'If you bought it, it\'s about to crash. You are the most reliable contrarian indicator in crypto.',
    emotionalTendency: 'Perpetual buyer\'s remorse with occasional false hope during dead cat bounces.',
    gradient: 'linear-gradient(135deg, #FACC15 0%, #EAB308 50%, #CA8A04 100%)',
    gradientColors: ['#FACC15', '#CA8A04'],
    accentColor: '#FACC15',
    traits: [
      { name: 'Risk Appetite', value: 75, color: '#FACC15' },
      { name: 'Conviction', value: 50, color: '#EAB308' },
      { name: 'Emotional Stability', value: 30, color: '#CA8A04' },
      { name: 'Meme Exposure', value: 70, color: '#FF4FD8' },
      { name: 'Patience', value: 20, color: '#7C5CFF' },
      { name: 'Diversification', value: 45, color: '#00D4FF' },
    ],
    icon: '🎯',
    mood: 'tragicomic',
  },
  {
    id: 'chaotic-ape',
    title: 'Chaotic Ape',
    emoji: '🦧',
    tagline: 'No analysis. No plan. Just vibes.',
    description: 'You ape into projects based on vibes, CT hype, and whether the logo looks cool. Your investment thesis is "it feels right." Your risk management is nonexistent. Your gains? Occasionally legendary.',
    strengths: ['Fearless execution', 'Early trend adoption', 'No analysis paralysis'],
    weaknesses: ['No strategy', 'All-in mentality', 'Portfolio concentration risk'],
    memeObservation: 'You saw a chart going up, bought it, then asked "what does this project do?" Classic.',
    emotionalTendency: 'Constant adrenaline. Your portfolio is a roller coaster and you never get off the ride.',
    gradient: 'linear-gradient(135deg, #F97316 0%, #EA580C 50%, #C2410C 100%)',
    gradientColors: ['#F97316', '#C2410C'],
    accentColor: '#F97316',
    traits: [
      { name: 'Risk Appetite', value: 100, color: '#F97316' },
      { name: 'Conviction', value: 60, color: '#EA580C' },
      { name: 'Emotional Stability', value: 25, color: '#C2410C' },
      { name: 'Meme Exposure', value: 80, color: '#FF4FD8' },
      { name: 'Patience', value: 5, color: '#7C5CFF' },
      { name: 'Diversification', value: 15, color: '#00D4FF' },
    ],
    icon: '🔥',
    mood: 'feral',
  },
  {
    id: 'gas-fee-minimalist',
    title: 'Gas Fee Minimalist',
    emoji: '⛽',
    tagline: 'Saving satoshis since genesis.',
    description: 'You wait for the perfect gas fee window like a sniper. You\'ve calculated the optimal time zone for cheap transactions. Every wei matters. You are the most efficient operator in crypto.',
    strengths: ['Cost optimization', 'Strategic patience', 'Efficiency obsession'],
    weaknesses: ['Misses opportunities waiting for gas', 'Over-optimizes small amounts', 'Penny wise, pound foolish'],
    memeObservation: 'You waited 6 hours for gas fees to drop 2 cents while the token pumped 300%. Efficiency king.',
    emotionalTendency: 'Calm, calculated, and mildly frustrated by anyone who pays market-rate gas fees.',
    gradient: 'linear-gradient(135deg, #2DD4BF 0%, #14B8A6 50%, #0D9488 100%)',
    gradientColors: ['#2DD4BF', '#0D9488'],
    accentColor: '#2DD4BF',
    traits: [
      { name: 'Risk Appetite', value: 30, color: '#2DD4BF' },
      { name: 'Conviction', value: 70, color: '#14B8A6' },
      { name: 'Emotional Stability', value: 85, color: '#0D9488' },
      { name: 'Meme Exposure', value: 10, color: '#FF4FD8' },
      { name: 'Patience', value: 90, color: '#7C5CFF' },
      { name: 'Diversification', value: 60, color: '#00D4FF' },
    ],
    icon: '💰',
    mood: 'methodical',
  },
  {
    id: 'midnight-gambler',
    title: 'Midnight Gambler',
    emoji: '🌙',
    tagline: 'The best trades happen at 3 AM.',
    description: 'You make your most consequential financial decisions at 3 AM, fueled by coffee and CT alpha. Your circadian rhythm is inverted, your judgment is questionable, and your late-night apes are the stuff of legend.',
    strengths: ['24/7 market coverage', 'Catching Asian/EU pumps', 'Dedication'],
    weaknesses: ['Sleep deprivation decisions', 'Night trades are riskier', 'Health concerns'],
    memeObservation: 'Your best and worst trades were both made at 3:47 AM. Your sleep schedule is as wrecked as your portfolio.',
    emotionalTendency: 'Manic late-night energy followed by morning regret. The "check portfolio first thing" person.',
    gradient: 'linear-gradient(135deg, #A78BFA 0%, #8B5CF6 50%, #7C3AED 100%)',
    gradientColors: ['#A78BFA', '#7C3AED'],
    accentColor: '#A78BFA',
    traits: [
      { name: 'Risk Appetite', value: 80, color: '#A78BFA' },
      { name: 'Conviction', value: 55, color: '#8B5CF6' },
      { name: 'Emotional Stability', value: 35, color: '#7C3AED' },
      { name: 'Meme Exposure', value: 65, color: '#FF4FD8' },
      { name: 'Patience', value: 30, color: '#7C5CFF' },
      { name: 'Diversification', value: 50, color: '#00D4FF' },
    ],
    icon: '🎰',
    mood: 'nocturnal',
  },
  {
    id: 'nft-archaeologist',
    title: 'NFT Archaeologist',
    emoji: '🏺',
    tagline: 'Your wallet is a museum of dead JPEGs.',
    description: 'You collected NFTs when they were "the future of digital ownership." Your wallet is a time capsule of 2021-2022 era projects. You have floor price PTSD but still believe in digital art.',
    strengths: ['Cultural curator', 'Early adopter mentality', 'Community builder'],
    weaknesses: ['Bag holder of dead projects', 'Emotional attachment to JPEGs', 'Overpaid for pixels'],
    memeObservation: 'You own 47 NFTs worth a combined $12. You still call yourself a "collector" and not a "bag holder."',
    emotionalTendency: 'Nostalgic and defensive. Will passionately argue that your Bored Ape is still worth it.',
    gradient: 'linear-gradient(135deg, #F472B6 0%, #EC4899 50%, #DB2777 100%)',
    gradientColors: ['#F472B6', '#DB2777'],
    accentColor: '#F472B6',
    traits: [
      { name: 'Risk Appetite', value: 55, color: '#F472B6' },
      { name: 'Conviction', value: 75, color: '#EC4899' },
      { name: 'Emotional Stability', value: 45, color: '#DB2777' },
      { name: 'Meme Exposure', value: 50, color: '#FF4FD8' },
      { name: 'Patience', value: 70, color: '#7C5CFF' },
      { name: 'Diversification', value: 40, color: '#00D4FF' },
    ],
    icon: '🖼️',
    mood: 'nostalgic',
  },
  {
    id: 'yield-chaser',
    title: 'Yield Chaser',
    emoji: '🌾',
    tagline: 'Following APY like a moth to flame.',
    description: 'If there\'s a pool with triple-digit APY, you\'ve already deposited. You farm yields across 14 protocols and have spreadsheets tracking your positions. You are the DeFi power user.',
    strengths: ['DeFi expertise', 'Spreadsheet mastery', 'Capital efficiency'],
    weaknesses: ['Impermanent loss denial', 'Chasing unsustainable yields', 'Smart contract risk'],
    memeObservation: 'You\'ve provided liquidity to a pool that offered 10,000% APY. The pool lasted 3 days. You were the liquidity.',
    emotionalTendency: 'Obsessively calculating returns. Checks dashboard every 15 minutes. Has notifications for APY changes.',
    gradient: 'linear-gradient(135deg, #34D399 0%, #10B981 50%, #059669 100%)',
    gradientColors: ['#34D399', '#059669'],
    accentColor: '#34D399',
    traits: [
      { name: 'Risk Appetite', value: 70, color: '#34D399' },
      { name: 'Conviction', value: 60, color: '#10B981' },
      { name: 'Emotional Stability', value: 55, color: '#059669' },
      { name: 'Meme Exposure', value: 30, color: '#FF4FD8' },
      { name: 'Patience', value: 45, color: '#7C5CFF' },
      { name: 'Diversification', value: 85, color: '#00D4FF' },
    ],
    icon: '📊',
    mood: 'analytical',
  },
  {
    id: 'emotional-swing-trader',
    title: 'Emotional Swing Trader',
    emoji: '🎢',
    tagline: 'Buy high on hype. Sell low on fear.',
    description: 'Your trading strategy is entirely governed by emotions. You buy when euphoric, sell when terrified, and hold when confused. Your chart annotations include motivational quotes and crying emojis.',
    strengths: ['Market sentiment radar', 'Quick decision making', 'Passionate engagement'],
    weaknesses: ['Emotion-driven trades', 'No stop losses', 'Revenge trading'],
    memeObservation: 'You\'ve written "THIS IS THE ONE" in your trading journal 47 times. It was never the one.',
    emotionalTendency: 'Emotional roller coaster. Your trading journal reads like a therapy session.',
    gradient: 'linear-gradient(135deg, #FF4FD8 0%, #D946EF 50%, #A855F7 100%)',
    gradientColors: ['#FF4FD8', '#A855F7'],
    accentColor: '#FF4FD8',
    traits: [
      { name: 'Risk Appetite', value: 85, color: '#FF4FD8' },
      { name: 'Conviction', value: 35, color: '#D946EF' },
      { name: 'Emotional Stability', value: 10, color: '#A855F7' },
      { name: 'Meme Exposure', value: 55, color: '#FF4FD8' },
      { name: 'Patience', value: 15, color: '#7C5CFF' },
      { name: 'Diversification', value: 35, color: '#00D4FF' },
    ],
    icon: '💔',
    mood: 'volatile',
  },
];

export function getRandomArchetype(seed?: string): Archetype {
  if (seed) {
    // Use wallet address as seed for consistent results
    let hash = 0;
    for (let i = 0; i < seed.length; i++) {
      const char = seed.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash = hash & hash;
    }
    const index = Math.abs(hash) % archetypes.length;
    return archetypes[index];
  }
  return archetypes[Math.floor(Math.random() * archetypes.length)];
}

export function getArchetypeById(id: string): Archetype | undefined {
  return archetypes.find(a => a.id === id);
}
